import { chromium } from 'playwright'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

const edgePath = 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
const browser = await chromium.launch({ executablePath: edgePath, headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 })
  await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: /가족 케어/ }).waitFor()
  await page.screenshot({ path: join(tmpdir(), 'lgdx-thinq-home.png'), fullPage: true })
  const nav = page.getByRole('navigation', { name: 'ThinQ 주요 메뉴' })
  await nav.getByRole('button', { name: '디바이스' }).click()
  await page.getByText('ThinQ 디바이스', { exact: true }).first().waitFor()
  await nav.getByRole('button', { name: /가족/ }).click()
  await page.getByRole('button', { name: '케어 어시스턴트 일정·배정 질문하기' }).waitFor()
  await page.screenshot({ path: join(tmpdir(), 'lgdx-family-hub.png'), fullPage: true })
  await page.getByRole('button', { name: /빠른 메뉴 열기/ }).click()
  for (const name of ['알림장 촬영', '일정 직접 입력', '케어 어시스턴트', '긴급 도움 요청']) await page.getByRole('menuitem', { name: new RegExp(name) }).waitFor()
  await page.screenshot({ path: join(tmpdir(), 'lgdx-fab-menu.png'), fullPage: true })
  await page.getByRole('menuitem', { name: /케어 어시스턴트/ }).click()
  await page.getByRole('textbox', { name: '케어 어시스턴트에게 질문' }).fill('확인할 알림 알려줘')
  await page.getByRole('button', { name: '보내기' }).click()
  await page.getByText(/현재 확인이 필요한 돌봄 정보는/).waitFor()
  await page.getByRole('button', { name: '뒤로 가기' }).click()
  await page.getByRole('button', { name: /플랜·결제/ }).click()
  await page.getByText(/실제 구독·결제·서버 플랜은 변경하지 않아요/).waitFor()
  await page.getByRole('button', { name: 'Pro 화면 체험', exact: true }).click()
  await page.getByRole('button', { name: 'Pro 화면 체험 중' }).waitFor()
  await page.getByRole('button', { name: '뒤로 가기' }).click()
  await page.getByRole('button', { name: /처음부터 시작 체험/ }).click()
  await page.getByRole('button', { name: '다음' }).click()
  await page.getByRole('button', { name: '조부모' }).click()
  await page.getByRole('button', { name: '다음' }).click()
  await page.getByRole('button', { name: '지우' }).click()
  await page.getByRole('button', { name: '가족 케어 시작' }).click()
  await page.getByRole('button', { name: '돌봄 정보' }).first().waitFor()
  const baseline = await page.evaluate(async () => (await (await fetch('/api/bootstrap')).json()).items.filter(item => item.status === 'NEEDS_REVIEW').length)
  let addReview = false
  await page.route('**/api/bootstrap', async route => {
    const response = await route.fetch()
    const data = await response.json()
    if (addReview) data.items.push({ id: 'qa-only-review', intake_id: null, child_id: data.children[0]?.id ?? null, item_type: 'TODO', title: 'QA 새 돌봄 정보', detail: '', starts_at: null, confidence: 'HIGH', status: 'NEEDS_REVIEW', created_at: new Date().toISOString() })
    await route.fulfill({ response, json: data })
  })
  await nav.getByRole('button', { name: '홈' }).click()
  if (baseline) await page.getByText(`확인 ${baseline}건`).waitFor()
  addReview = true
  await nav.getByRole('button', { name: '홈' }).click()
  await page.getByText(`확인 ${baseline + 1}건`).waitFor()
  await nav.getByRole('button', { name: /가족/ }).click()
  await page.getByRole('button', { name: /빠른 메뉴 열기/ }).click()
  await page.getByRole('menuitem', { name: /알림장 촬영/ }).click()
  const [cameraChooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: '사진 촬영' }).click()])
  if (await (await cameraChooser.element()).getAttribute('capture') !== 'environment') throw new Error('촬영 버튼이 후면 카메라 입력으로 연결되지 않았어요')
  await cameraChooser.setFiles(join(process.cwd(), '..', 'asset', 'Group 21.png'))
  await page.getByRole('img', { name: '선택한 알림장' }).waitFor()
  const [uploadChooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: '사진 업로드', exact: true }).click()])
  if (await (await uploadChooser.element()).getAttribute('capture')) throw new Error('업로드 버튼이 카메라 입력으로 연결됐어요')
  await uploadChooser.setFiles(join(process.cwd(), '..', 'asset', 'Group 21.png'))
  await page.screenshot({ path: join(tmpdir(), 'lgdx-photo-capture.png'), fullPage: true })
  console.log('Mobile flow passed: ThinQ tabs, Family hub, FAB, assistant, Pro switch, onboarding, dynamic summary, camera/upload preview')
} finally {
  await browser.close()
}
