import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { api, send, formatDate, formatTime, type Assignment, type Bootstrap, type CareItem, type Screen, type Suggestion } from './api'

const groups: { title: string; pages: [Screen, string][] }[] = [
  { title: '핵심 화면', pages: [['home', '홈 대시보드'], ['family', 'Family Inbox'], ['capture', '알림장 등록'], ['review', '추출 결과 확인'], ['assignments', '오늘의 배정'], ['suggestion', '배정 제안'], ['tasks', '오늘 할 일']] },
  { title: '돌봄 흐름', pages: [['schedule', '개인 일정'], ['exception', '예외 상황'], ['handoff', '인수인계'], ['notifications', '알림함']] },
  { title: '가족 · 설정', pages: [['onboarding', '온보딩'], ['calendar', '캘린더 연동'], ['members', '가족 구성원'], ['permissions', '정보 공개 권한'], ['settings', '알림 설정'], ['plan', '플랜 비교']] },
  { title: '확장 화면', pages: [['chat', 'AI 채팅'], ['emergency', '긴급 요청'], ['location', '돌봄 동선'], ['gap', '돌봄 공백 예측'], ['album', '패밀리 앨범'], ['programs', '돌봄 제도']] },
]
const typeLabel: Record<string, string> = { SCHEDULE: '일정', SUPPLY: '준비물', TODO: '할 일', CHANGE: '변경사항' }
const localDateTime = (value: string | null) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60_000).toISOString().slice(0, 16) : ''

function Card({ children, className = '', onClick }: { children: ReactNode; className?: string; onClick?: () => void }) {
  return <div className={'card ' + className} onClick={onClick}>{children}</div>
}
function Section({ children, action }: { children: ReactNode; action?: ReactNode }) {
  return <div className="section-heading"><span>{children}</span>{action}</div>
}
function Empty({ title, text }: { title: string; text: string }) {
  return <Card className="empty"><span className="empty-glyph">✓</span><strong>{title}</strong><p>{text}</p></Card>
}
function Pro() { return <span className="pro-badge">PRO</span> }

function App() {
  const [boot, setBoot] = useState<Bootstrap | null>(null)
  const [screen, setScreen] = useState<Screen>('home')
  const [error, setError] = useState('')
  const [toast, setToast] = useState('')
  const [filter, setFilter] = useState('all')
  const [viewer, setViewer] = useState('mom')
  const [itemId, setItemId] = useState<string | null>(null)
  const [assignmentId, setAssignmentId] = useState<string | null>(null)
  const [suggestions, setSuggestions] = useState<Suggestion[]>([])
  const [reviewTitle, setReviewTitle] = useState('')
  const [reviewType, setReviewType] = useState('TODO')
  const [reviewStart, setReviewStart] = useState('')
  const [captureText, setCaptureText] = useState('')
  const [captureChild, setCaptureChild] = useState('jiu')
  const [captureFile, setCaptureFile] = useState('')
  const [scheduleTitle, setScheduleTitle] = useState('')
  const [scheduleMember, setScheduleMember] = useState('mom')
  const [scheduleStart, setScheduleStart] = useState('')
  const [scheduleEnd, setScheduleEnd] = useState('')
  const [memberNameInput, setMemberNameInput] = useState('')
  const [memberRole, setMemberRole] = useState('GRANDPARENT')
  const [permissionMember, setPermissionMember] = useState('grandma')
  const [note, setNote] = useState('')
  const [showSheet, setShowSheet] = useState(false)
  const [alternative, setAlternative] = useState('grandma')
  const [reason, setReason] = useState('일정이 겹쳐 다른 담당자가 필요해요')

  const load = async () => setBoot(await api<Bootstrap>('/bootstrap'))
  useEffect(() => { api<Bootstrap>('/bootstrap').then(setBoot).catch((e: Error) => setError(e.message)) }, [])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3200); return () => clearTimeout(timer) } }, [toast])
  const run = async (work: () => Promise<unknown>, message: string) => {
    try { setError(''); await work(); await load(); setToast(message) }
    catch (e) { setError((e as Error).message) }
  }
  const go = (target: Screen) => { setError(''); setScreen(target) }
  const members = boot?.members.filter(member => member.status === 'ACTIVE') ?? []
  const member = (id: string) => boot?.members.find(m => m.id === id)?.name ?? '가족'
  const child = (id: string | null) => boot?.children.find(c => c.id === id)?.name ?? '가족'
  const items = boot?.items.filter(i => filter === 'all' || i.child_id === filter) ?? []
  const pending = items.filter(i => i.status === 'NEEDS_REVIEW')
  const assignments = boot?.assignments.filter(a => !['CANCELED', 'REJECTED'].includes(a.status)) ?? []
  const activeItem = boot?.items.find(i => i.id === itemId) ?? null
  const activeAssignment = boot?.assignments.find(a => a.id === assignmentId) ?? null
  const unread = boot?.notifications.filter(n => !n.is_read).length ?? 0
  const preference = boot?.notification_preferences.find(p => p.member_id === viewer)
  const appNotices = !!(preference?.app_enabled ?? 1)
  const dailyDigest = !!(preference?.daily_digest_enabled ?? 1)
  const title = groups.flatMap(g => g.pages).find(([id]) => id === screen)?.[1] ?? '가족'
  const today = new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date())

  const openReview = (item: CareItem) => { setItemId(item.id); setReviewTitle(item.title); setReviewType(item.item_type); setReviewStart(localDateTime(item.starts_at)); go('review') }
  const openSuggestion = async (item: CareItem) => {
    try { const result = await api<{ suggestions: Suggestion[] }>('/items/' + item.id + '/suggestions'); setItemId(item.id); setSuggestions(result.suggestions); go('suggestion') }
    catch (e) { setError((e as Error).message) }
  }
  const capture = () => run(async () => {
    if (!captureText.trim()) throw new Error('알림장 내용을 입력해주세요')
    const result = await send<{ items: CareItem[] }>('/intakes', 'POST', { child_id: captureChild, raw_content: captureText.trim(), input_type: captureFile ? 'PHOTO_TRANSCRIPT' : 'TEXT' })
    if (result.items[0]) { setItemId(result.items[0].id); setReviewTitle(result.items[0].title); setReviewType(result.items[0].item_type); setReviewStart(localDateTime(result.items[0].starts_at)) }
    setCaptureText(''); setCaptureFile(''); go('review')
  }, '확인할 항목을 정리했어요')
  const saveReview = () => run(async () => {
    if (!activeItem) return
    await send('/items/' + activeItem.id, 'PATCH', { title: reviewTitle, item_type: reviewType, ...(reviewStart ? { starts_at: new Date(reviewStart).toISOString() } : {}) })
    await send('/items/' + activeItem.id + '/confirm', 'POST')
    go('family')
  }, '돌봄 정보를 저장했어요')
  const saveSchedule = () => run(async () => {
    if (!scheduleTitle || !scheduleStart || !scheduleEnd) throw new Error('일정 정보를 모두 입력해주세요')
    const result = await send<{ collisions: unknown[] }>('/schedules', 'POST', { member_id: scheduleMember, title: scheduleTitle, starts_at: new Date(scheduleStart).toISOString(), ends_at: new Date(scheduleEnd).toISOString() })
    setScheduleTitle(''); setScheduleStart(''); setScheduleEnd('')
    if (result.collisions.length) go('exception')
  }, '개인 일정을 등록했어요')
  const complete = () => run(async () => {
    if (!activeAssignment) return
    await send('/assignments/' + activeAssignment.id + '/complete', 'POST', { note })
    setShowSheet(false); setNote('')
  }, '완료를 가족에게 알렸어요')

  const tabs = boot && <div className="child-tabs"><button className={filter === 'all' ? 'selected' : ''} onClick={() => setFilter('all')}>전체</button>{boot.children.map(c => <button key={c.id} className={filter === c.id ? 'selected' : ''} onClick={() => setFilter(c.id)}>{c.name} ({c.age_label})</button>)}</div>
  const itemFor = (a: Assignment) => boot?.items.find(i => i.id === a.item_id)
  const timeline = (list: Assignment[]) => <Card className="timeline-card">{[...list].sort((a, b) => (itemFor(a)?.starts_at || '').localeCompare(itemFor(b)?.starts_at || '')).map(a => { const i = itemFor(a); return i && <button key={a.id} className="timeline-row" onClick={() => { setAssignmentId(a.id); go('tasks') }}><span className="time">{formatTime(i.starts_at) || '—'}</span><span className="timeline-content"><strong>{i.title} — {member(a.assignee_id)}</strong><small>{a.status === 'COMPLETED' ? '완료' : a.status === 'PROPOSED' ? '수락 대기' : '진행 중'}</small></span><span className="timeline-status">{a.status === 'COMPLETED' ? '✓' : '›'}</span></button> })}</Card>

  let page: ReactNode = <div className="loading">가족의 하루를 불러오고 있어요</div>
  if (boot && screen === 'home') page = <>
    <Card className="travel-card" onClick={() => go('location')}><span className="travel-symbol">↗</span><div><strong>할머니와 태권도로 이동 중</strong><p>10분 후 도착 예정 · 동선 보기</p></div><span className="chevron">›</span></Card>
    {pending.length > 0 && <Card className="attention-card" onClick={() => go('family')}><div><span className="small-badge danger">확인 {pending.length}</span><strong>하원 시간 변경 · 일정 충돌</strong></div><span className="chevron">›</span></Card>}
    <Section action={<button className="text-link" onClick={() => go('assignments')}>전체 보기 ›</button>}>오늘 배정</Section>{timeline(assignments.filter(a => ['dropoff', 'pickup', 'dinner'].includes(a.item_id)))}
    <Section>내일 미리 보기</Section><Card className="preview-card" onClick={() => go('assignments')}><span className="preview-icon">!</span><div><strong>준비물 ‘도화지’가 아직 없어요</strong><p>필요한 가족에게만 알려드려요</p></div><span className="chevron">›</span></Card>{tabs}
  </>
  if (boot && screen === 'family') page = <>{tabs}
    {pending.length > 0 && <Card className="inbox-summary" onClick={() => pending[0] && openReview(pending[0])}><span className="summary-dot">●</span><div><strong>오늘 들어온 정보 {pending.length + 1}건, 확인해주세요</strong><p>하루 1회 모아서 알려드려요 · 21:00</p></div><span className="chevron">›</span></Card>}
    <Section>확인 필요 {pending.length}</Section>{pending.length ? pending.map(i => <Card key={i.id} className="review-card"><div className="review-meta"><span className="child-pill">{child(i.child_id)}</span><span>신뢰도 낮음 · {typeLabel[i.item_type]}</span></div><strong>{i.title}</strong><p>{i.detail || '추출된 내용을 확인해주세요'}</p><div className="card-actions"><button onClick={() => openReview(i)}>확인하기</button><button onClick={() => setToast('나중에 다시 확인할 수 있어요')}>나중에</button></div></Card>) : <Empty title="확인할 것이 없어요" text="새로운 알림장이 들어오면 이곳에 표시돼요" />}
    <Section>확정된 일정</Section>{items.filter(i => ['CONFIRMED', 'ASSIGNED', 'DONE'].includes(i.status)).slice(0, 3).map(i => <Card key={i.id} className="schedule-card"><span className="time">{formatTime(i.starts_at) || '—'}</span><div><strong>{i.title} · {child(i.child_id)}</strong><p>{i.detail}</p></div><span className="green-check">✓</span></Card>)}
    <div className="inbox-buttons"><button className="primary-button" onClick={() => go('capture')}>알림장 촬영</button><button className="outline-button" onClick={() => go('capture')}>직접 입력</button></div>
  </>
  if (boot && screen === 'capture') page = <><div className="eyebrow">FAMILY INBOX</div><h2 className="hero-title">흩어진 안내를<br />한 번에 정리해요</h2><p className="hero-copy">알림장, 문자, 가정통신문에 적힌 돌봄 정보를 모아주세요.</p>
    <label className="capture-frame"><input type="file" accept="image/*" capture="environment" onChange={e => setCaptureFile(e.target.files?.[0]?.name ?? '')} /><span className="camera-glyph">▣</span><strong>{captureFile || '알림장 사진 선택'}</strong><small>사진을 보며 내용을 확인할 수 있어요</small></label>
    <Section>아이 선택</Section><div className="choice-row">{boot.children.map(c => <button key={c.id} className={'choice-chip ' + (captureChild === c.id ? 'active' : '')} onClick={() => setCaptureChild(c.id)}>{c.name}</button>)}</div>
    <label className="form-label">돌봄 정보 입력</label><textarea className="text-area" rows={5} value={captureText} onChange={e => setCaptureText(e.target.value)} placeholder={'예: 금요일 하원 시간이 15시로 변경\n준비물: 도시락, 모자'} /><p className="helper-text">날짜, 준비물, 해야 할 일을 한 줄씩 적어주세요.</p><button className="primary-button wide-button" onClick={capture}>내용 정리하기</button>
  </>
  if (boot && screen === 'review') page = <><div className="eyebrow">추출 결과 확인</div><h2 className="hero-title">표시된 부분만<br />확인해주세요</h2><p className="hero-copy">틀린 부분만 고치고 저장하면 돼요.</p>
    <div className="review-switcher">{boot.items.filter(i => i.status === 'NEEDS_REVIEW').slice(0, 8).map(i => <button key={i.id} className={itemId === i.id ? 'active' : ''} onClick={() => openReview(i)}>{typeLabel[i.item_type]}</button>)}</div>
    {activeItem && <Card className="detail-review-card"><div className="review-meta"><span className={'confidence ' + (activeItem.confidence === 'HIGH' ? 'high' : 'low')}>{activeItem.confidence === 'HIGH' ? '✓ 신뢰도 높음' : '! 신뢰도 낮음'}</span><span>{child(activeItem.child_id)}</span></div><label className="form-label">항목 종류</label><select className="form-control" value={reviewType} onChange={e => setReviewType(e.target.value)}>{Object.entries(typeLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><label className="form-label">내용</label><input className="form-control" value={reviewTitle} onChange={e => setReviewTitle(e.target.value)} /><label className="form-label">돌봄 예정 일시 (선택)</label><input className="form-control" type="datetime-local" value={reviewStart} onChange={e => setReviewStart(e.target.value)} /><p className="helper-text">일시를 입력하면 가족 일정과 겹치는지 확인할 수 있어요.</p><p className="source-text">출처 · {activeItem.intake_id ? '등록한 돌봄 정보' : '별빛유치원 알림장'}</p></Card>}
    <button className="primary-button wide-button" disabled={!activeItem} onClick={saveReview}>확인하고 저장</button>
  </>
  if (boot && screen === 'assignments') page = <><div className="eyebrow">ROLE MATCH</div><h2 className="hero-title">오늘의 배정</h2><p className="hero-copy">평소대로인 배정은 조용히 진행하고, 조정할 일만 알려드려요.</p><Section>확정된 배정</Section>{timeline(assignments)}<Section>배정이 필요한 일</Section>{items.filter(i => i.status === 'CONFIRMED' && !assignments.some(a => a.item_id === i.id)).map(i => <Card key={i.id} className="suggest-card" onClick={() => openSuggestion(i)}><div><strong>{i.title}</strong><p>{child(i.child_id)} · {formatTime(i.starts_at) || '시간 미정'}</p></div><span className="chevron">›</span></Card>)}<Card className="info-note" onClick={() => go('schedule')}>개인 일정을 등록하면 가능한 시간을 참고해요 ›</Card></>
  if (boot && screen === 'suggestion') page = <><div className="eyebrow">배정 제안</div><h2 className="hero-title">{activeItem?.title || '내일 등원'}</h2><p className="hero-copy">가능한 가족에게 요청해보세요. 수락 전까지 배정은 확정되지 않습니다.</p>{suggestions.map(s => <Card key={s.member_id} className={'person-card ' + (s.priority === 1 ? 'recommended' : '')}><div className="person-avatar">{s.name.slice(0, 1)}</div><div className="person-info"><strong>{s.name}</strong><p>{s.reason}</p></div><span className={'small-badge ' + (s.available ? 'ok' : 'danger')}>{s.available ? s.priority + '순위' : '바쁨'}</span><button className={s.priority === 1 ? 'primary-button' : 'outline-button'} disabled={!s.available || !activeItem} onClick={() => run(async () => { await send('/assignments', 'POST', { item_id: activeItem!.id, assignee_id: s.member_id }); go('assignments') }, s.name + '님에게 요청했어요')}>{s.name}에게 요청</button></Card>)}<Section>판단 근거</Section><Card className="reason-card"><p>등록된 개인 일정과 돌봄 시간을 비교했어요.</p><p>캘린더는 바쁨/한가함만 참고합니다 (Level A).</p></Card></>
  if (boot && screen === 'tasks') page = <><div className="viewer-switch"><span>담당자 보기</span><select value={viewer} onChange={e => setViewer(e.target.value)}>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></div><Card className="task-summary"><span className="green-check">✓</span><div><strong>오늘 맡은 일 {assignments.filter(a => a.assignee_id === viewer).length}건</strong><p>끝난 일은 가족에게 바로 알려드려요</p></div></Card><Section>오늘 할 일</Section>{assignments.filter(a => a.assignee_id === viewer).map(a => { const i = itemFor(a); return i && <Card key={a.id} className="task-card"><div className="task-top"><span className="time">{formatTime(i.starts_at) || '시간 미정'}</span><span className="small-badge ok">{a.status === 'COMPLETED' ? '완료' : a.status === 'PROPOSED' ? '수락 대기' : '담당'}</span></div><strong>{i.title} — {child(i.child_id)}</strong><p>{i.detail}</p>{a.status === 'PROPOSED' ? <div className="task-actions"><button className="primary-button" onClick={() => run(() => send('/assignments/' + a.id + '/respond', 'POST', { decision: 'ACCEPTED' }), '배정을 수락했어요')}>맡을게요</button><button className="outline-button" onClick={() => run(() => send('/assignments/' + a.id + '/respond', 'POST', { decision: 'REJECTED' }), '다른 담당자를 찾을게요')}>어려워요</button></div> : a.status === 'ACCEPTED' ? <button className="primary-button wide-button" onClick={() => { setAssignmentId(a.id); setShowSheet(true) }}>완료 체크</button> : <p className="source-text">{a.note ? '특이사항 · ' + a.note : '특이사항 없음'}</p>}</Card> })}<Section>이번 주 내 담당</Section><Card className="stats-card"><div><strong>{assignments.filter(a => a.assignee_id === viewer).length}</strong><span>맡은 일</span></div><div><strong>{assignments.filter(a => a.assignee_id === viewer && a.status === 'COMPLETED').length}</strong><span>완료</span></div><div><strong>{assignments.filter(a => a.assignee_id === viewer && a.note).length}</strong><span>특이사항</span></div></Card></>
  if (boot && screen === 'schedule') page = <><div className="eyebrow">개인 일정 등록</div><h2 className="hero-title">바쁜 시간을<br />알려주세요</h2><p className="hero-copy">배정에 필요한 가능 여부만 가족에게 반영돼요.</p><Card className="form-card"><label className="form-label">일정 이름</label><input className="form-control" value={scheduleTitle} onChange={e => setScheduleTitle(e.target.value)} placeholder="예: 오전 회의" /><label className="form-label">구성원</label><select className="form-control" value={scheduleMember} onChange={e => setScheduleMember(e.target.value)}>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><label className="form-label">시작</label><input className="form-control" type="datetime-local" value={scheduleStart} onChange={e => setScheduleStart(e.target.value)} /><label className="form-label">종료</label><input className="form-control" type="datetime-local" value={scheduleEnd} onChange={e => setScheduleEnd(e.target.value)} /></Card><button className="primary-button wide-button" onClick={saveSchedule}>일정 등록</button><Section>등록된 일정</Section>{boot.schedules.map(s => <Card key={s.id} className="simple-list-card"><span className="calendar-icon">▦</span><div><strong>{s.title}</strong><p>{member(s.member_id)} · {formatDate(s.starts_at)} {formatTime(s.starts_at)}</p></div></Card>)}</>
  if (boot && screen === 'exception') page = <><div className="eyebrow urgent">EXCEPTION CARE</div><h2 className="hero-title">지금 확인이<br />필요해요</h2><Card className="urgent-card"><span className="small-badge danger">일정 충돌 감지</span><strong>담당자의 일정이 돌봄 시간과 겹쳤어요.</strong><p>하원 마감 전까지 다른 담당자를 정해 주세요.</p></Card><Section>진행 중인 대안</Section>{boot.exceptions.length ? boot.exceptions.map(e => <Card key={e.id} className="exception-card"><strong>{e.reason}</strong><p>대안 · {member(e.alternative_member_id)}</p><span className="small-badge ok">{e.status === 'PENDING' ? '확인 대기' : '승인됨'}</span>{e.status === 'PENDING' && <button className="primary-button" onClick={() => run(() => send('/exceptions/' + e.id + '/approve', 'POST'), '대안을 요청했어요')}>대안 승인</button>}</Card>) : <Empty title="새로운 대안이 없어요" text="충돌이 생기면 해결책을 이곳에서 확인할 수 있어요" />}<Section>직접 대안 제안</Section><Card className="form-card"><label className="form-label">조정할 배정</label><select className="form-control" value={assignmentId || ''} onChange={e => setAssignmentId(e.target.value)}><option value="">배정을 선택하세요</option>{assignments.filter(a => a.status === 'ACCEPTED').map(a => <option key={a.id} value={a.id}>{itemFor(a)?.title} · {member(a.assignee_id)}</option>)}</select><label className="form-label">다른 담당자</label><select className="form-control" value={alternative} onChange={e => setAlternative(e.target.value)}>{members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><label className="form-label">사유</label><input className="form-control" value={reason} onChange={e => setReason(e.target.value)} /><button className="primary-button wide-button" onClick={() => run(async () => { if (!assignmentId) throw new Error('배정을 선택해주세요'); await send('/exceptions', 'POST', { assignment_id: assignmentId, alternative_member_id: alternative, reason }) }, '대안을 등록했어요')}>대안 만들기</button></Card></>
  if (boot && screen === 'handoff') page = <><div className="eyebrow">CARE HANDOFF</div><h2 className="hero-title">필요한 정보만<br />이어드려요</h2><p className="hero-copy">담당자가 바뀔 때 지금 필요한 내용을 간단히 전달해요.</p><Section>인수인계 브리핑</Section>{boot.handoffs.length ? boot.handoffs.map(h => <Card key={h.id} className="handoff-card"><div className="handoff-avatars"><span>엄</span><span>→</span><span>{member(h.to_member_id).slice(0, 1)}</span></div><strong>{h.briefing}</strong><p>{member(h.to_member_id)}님에게 전달</p><div className="card-actions"><span className="small-badge ok">{h.status === 'PENDING' ? '확인 대기' : '확인 완료'}</span>{h.status === 'PENDING' && <button onClick={() => run(() => send('/handoffs/' + h.id + '/acknowledge', 'POST'), '인수인계를 확인했어요')}>인수인계 받았어요</button>}</div></Card>) : <Empty title="인수인계 대기 항목이 없어요" text="담당 배정이 확정되면 브리핑이 나타나요" />}<Card className="info-note">특이사항은 다음 담당자에게 이어져요.</Card></>
  if (boot && screen === 'notifications') page = <><div className="eyebrow">알림함</div><h2 className="hero-title">필요한 소식만<br />전해드려요</h2><Section>새 알림 {unread}</Section>{boot.notifications.map(n => <Card key={n.id} className={'notice-card ' + (n.is_read ? 'read' : '')} onClick={() => !n.is_read && run(() => send('/notifications/' + n.id + '/read', 'PATCH'), '읽음으로 표시했어요')}><span className={'notice-mark ' + (n.level === 'IMPORTANT' ? 'important' : '')}>{n.level === 'IMPORTANT' ? '!' : '✓'}</span><div><strong>{n.title}</strong><p>{n.body}</p><small>{formatDate(n.created_at)} {formatTime(n.created_at)}</small></div>{!n.is_read && <span className="unread-dot" />}</Card>)}<button className="text-link centered" onClick={() => go('settings')}>알림 설정</button></>
  if (boot && screen === 'members') page = <><div className="eyebrow">우리 가족</div><h2 className="hero-title">돌봄 구성원</h2><p className="hero-copy">가전 사용 권한과 돌봄 정보 권한은 따로 관리해요.</p><Section>가족 구성원</Section>{boot.members.map(m => <Card key={m.id} className="member-card"><div className="person-avatar">{m.name.slice(0, 1)}</div><div><strong>{m.name}</strong><p>{m.role === 'GRANDPARENT' ? '조부모' : '부모'} · {m.status === 'ACTIVE' ? '참여 중' : '초대 대기'}</p></div>{m.status === 'PENDING' && <button className="text-link" onClick={() => run(() => send('/members/' + m.id + '/accept', 'POST'), '가족에 합류했어요')}>합류</button>}</Card>)}<Section>아이</Section>{boot.children.map(c => <Card key={c.id} className="member-card"><div className="child-avatar">{c.name.slice(0, 1)}</div><div><strong>{c.name}</strong><p>{c.age_label}</p></div></Card>)}<Section>구성원 초대</Section><Card className="form-card"><label className="form-label">이름</label><input className="form-control" value={memberNameInput} onChange={e => setMemberNameInput(e.target.value)} placeholder="가족 이름" /><label className="form-label">역할</label><select className="form-control" value={memberRole} onChange={e => setMemberRole(e.target.value)}><option value="PARENT">부모</option><option value="GRANDPARENT">조부모</option><option value="CAREGIVER">돌봄 참여자</option></select><button className="primary-button wide-button" onClick={() => run(async () => { if (!memberNameInput.trim()) throw new Error('이름을 입력해주세요'); await send('/members', 'POST', { name: memberNameInput.trim(), role: memberRole }); setMemberNameInput('') }, '초대 대기 구성원을 추가했어요')}>구성원 추가</button></Card><button className="text-link centered" onClick={() => go('permissions')}>정보 공개 권한 관리</button></>
  if (boot && screen === 'onboarding') page = <><div className="eyebrow">FAMILY CARE · 시작하기</div><h2 className="hero-title">가족의 돌봄을<br />끊김 없이 이어요</h2><p className="hero-copy">흩어진 안내를 모으고, 맡을 일을 나누고, 완료까지 함께 확인해요.</p><Card className="onboarding-art"><span className="onboard-circle a">엄</span><span className="onboard-line">→</span><span className="onboard-circle b">할</span><span className="onboard-line">→</span><span className="onboard-circle c">아</span></Card><Section>가족 안에서 내 역할</Section><div className="choice-row"><button className="choice-chip active">부모</button><button className="choice-chip" onClick={() => setToast('초대 코드로 가족에 합류할 수 있어요')}>조부모</button><button className="choice-chip" onClick={() => setToast('초대 코드로 가족에 합류할 수 있어요')}>돌봄 참여자</button></div><Card className="info-note">ThinQ 계정으로 시작하고, 돌봄 정보 공개 권한은 따로 설정해요.</Card><button className="primary-button wide-button" onClick={() => go('members')}>가족 설정 시작</button><button className="text-link centered" onClick={() => go('home')}>나중에 하기</button></>
  if (boot && screen === 'calendar') page = <><div className="eyebrow">업무 캘린더 연결</div><h2 className="hero-title">가능한 시간만<br />참고할게요</h2><p className="hero-copy">개인 일정 내용 대신 돌봄 배정에 필요한 바쁨/한가함만 사용해요 (Level A).</p><Card className="calendar-provider" onClick={() => setToast('캘린더 연결 안내가 준비되면 알려드릴게요')}><span className="provider-mark google">G</span><div><strong>Google Calendar</strong><p>업무 일정 연결</p></div><span className="chevron">›</span></Card><Card className="calendar-provider" onClick={() => setToast('캘린더 연결 안내가 준비되면 알려드릴게요')}><span className="provider-mark outlook">O</span><div><strong>Outlook Calendar</strong><p>업무 일정 연결</p></div><span className="chevron">›</span></Card><Card className="info-note">캘린더 연결을 건너뛰어도 직접 일정을 등록할 수 있어요.</Card><button className="primary-button wide-button" onClick={() => go('schedule')}>직접 일정 등록</button></>
  if (boot && screen === 'permissions') page = <><div className="eyebrow">정보 공개 권한</div><h2 className="hero-title">필요한 정보만<br />보여드려요</h2><p className="hero-copy">구성원마다 볼 수 있는 정보를 선택해 주세요.</p><div className="choice-row">{members.map(m => <button key={m.id} className={'choice-chip ' + (permissionMember === m.id ? 'active' : '')} onClick={() => setPermissionMember(m.id)}>{m.name}</button>)}</div><Section>{member(permissionMember)}님의 열람 범위</Section>{[['CHILD_DETAIL', '아이 정보', '이름과 돌봄 일정'], ['LOCATION', '위치', '이동과 인수인계 위치'], ['HEALTH', '건강 정보', '복약과 건강 관련 내용'], ['NOTE', '특이사항', '돌봄 완료 메모'], ['PHOTO', '사진', '완료 사진과 앨범']].map(([scope, name, detail]) => { const allowed = !!boot.permissions.find(p => p.member_id === permissionMember && p.scope === scope)?.is_allowed; return <Card key={scope} className="permission-row"><div><strong>{name}</strong><p>{detail}</p></div><button className={'switch ' + (allowed ? 'on' : '')} role="switch" aria-checked={allowed} aria-label={name + ' 공개'} onClick={() => run(() => send('/members/' + permissionMember + '/permissions', 'PATCH', { scope, is_allowed: !allowed }), '공개 범위를 변경했어요')}><span /></button></Card> })}<Card className="info-note">위치와 건강 정보는 기본적으로 공개하지 않아요.</Card></>
  if (boot && screen === 'settings') page = <><div className="eyebrow">알림 설정</div><h2 className="hero-title">조용하지만<br />놓치지 않게</h2><p className="hero-copy">평소대로 진행될 때는 알림을 줄이고, 확인할 때 알려드려요.</p><Section>앱 알림</Section><Card className="permission-row"><div><strong>돌봄 알림 받기</strong><p>등록, 배정, 인수인계, 완료</p></div><button className={'switch ' + (appNotices ? 'on' : '')} role="switch" aria-checked={appNotices} aria-label="돌봄 알림 받기" onClick={() => run(() => send('/members/' + viewer + '/notification-preferences', 'PATCH', { app_enabled: !appNotices }), '알림 설정을 변경했어요')}><span /></button></Card><Card className="permission-row"><div><strong>하루 1회 모아보기</strong><p>21:00에 확인할 정보만 요약</p></div><button className={'switch ' + (dailyDigest ? 'on' : '')} role="switch" aria-checked={dailyDigest} aria-label="하루 1회 모아보기" onClick={() => run(() => send('/members/' + viewer + '/notification-preferences', 'PATCH', { daily_digest_enabled: !dailyDigest }), '모아보기 설정을 변경했어요')}><span /></button></Card><Section>가전 알림 <Pro /></Section><Card className="permission-row" onClick={() => go('plan')}><div><strong>ThinQ 가전으로 알림</strong><p>집에 있을 때 TV·정수기에서 안내</p></div><span className="chevron">›</span></Card></>
  if (boot && screen === 'plan') page = <><div className="eyebrow">플랜 비교</div><h2 className="hero-title">우리 가족에게<br />맞는 돌봄</h2><p className="hero-copy">기본 돌봄 흐름은 무료로 사용할 수 있어요.</p><Card className="plan-card current"><span className="small-badge ok">현재 이용 중</span><h3>Family Care Free</h3><strong className="price">무료</strong><p>구성원 3명 · 자녀 2명</p><p>알림장 사진 등록 하루 2회</p><p>Family Inbox · Role Match · 완료 확인</p></Card><Card className="plan-card pro"><Pro /><h3>Family Care Pro</h3><strong className="price">더 넓은 가족 돌봄</strong><p>긴급 요청 · 가전 알림 · 음성 입력</p><p>돌봄 공백 예측 · 패밀리 앨범 · 지원 제도</p><button className="outline-button wide-button" onClick={() => setToast('플랜 안내가 준비되면 알려드릴게요')}>출시 알림 받기</button></Card></>
  if (boot && screen === 'chat') page = <><div className="eyebrow">AI 가족 운영 에이전트</div><Card className="chat-intro"><span className="agent-mark">✦</span><strong>무엇을 도와드릴까요?</strong><p>일정과 돌봄 배정을 한눈에 물어볼 수 있어요.</p></Card><div className="chat-bubble agent">내일 아빠가 8시 회의라 등원이 어려워 보여요. 할머니에게 요청해볼까요?</div><Card className="info-note">대화 기능은 Family Care Pro에서 제공될 예정이에요.</Card></>
  if (boot && screen === 'emergency') page = <><div className="eyebrow urgent">긴급 도움 요청 <Pro /></div><h2 className="hero-title">갑자기 돌봄이<br />어려워졌나요?</h2><p className="hero-copy">가능한 가족에게 동시에 요청하고, 먼저 응답한 사람을 확정해요.</p><Card className="urgent-card"><strong>하원 담당자를 급하게 찾고 있어요</strong><p>가족 전체에게 한 번에 요청할 수 있어요.</p></Card><button className="primary-button wide-button" onClick={() => go('plan')}>Pro 기능 살펴보기</button></>
  if (boot && screen === 'location') page = <><div className="eyebrow">돌봄 동선</div><h2 className="hero-title">지금 어디쯤<br />오고 있나요?</h2><p className="hero-copy">인수인계된 위치와 이동 시간을 한눈에 확인해요.</p><div className="map-panel"><div className="map-road one" /><div className="map-road two" /><span className="map-pin school">학교</span><span className="map-pin academy">태권도</span><span className="map-pin home">집</span><span className="map-route" /></div><Card className="route-card"><strong>학교 → 태권도</strong><p>할머니와 이동 중 · 10분 후 도착 예정</p><div className="route-progress"><span /></div></Card></>
  if (boot && screen === 'gap') page = <><div className="eyebrow">돌봄 공백 예측 <Pro /></div><h2 className="hero-title">방학 14일 전,<br />미리 준비해요</h2><p className="hero-copy">학교 일정과 가족의 가능 시간을 보고 돌봄이 비는 날을 찾아요.</p><Card className="gap-card"><span className="small-badge danger">D-14</span><strong>7월 셋째 주 오후 돌봄 공백 예상</strong><p>하교 후 15:00~17:30 사이 담당자가 필요해요.</p></Card><Section>가능한 대안</Section><Card className="simple-list-card"><span className="calendar-icon">▦</span><div><strong>늘봄학교 연장</strong><p>학교에서 이어지는 방과 후 돌봄</p></div></Card><Card className="simple-list-card"><span className="calendar-icon">♡</span><div><strong>지역 프로그램</strong><p>가족 동선과 맞는 수업 확인</p></div></Card><button className="primary-button wide-button" onClick={() => go('plan')}>Pro 기능 살펴보기</button></>
  if (boot && screen === 'album') page = <><div className="eyebrow">패밀리 앨범 <Pro /></div><h2 className="hero-title">가족의 순간을<br />함께 모아요</h2><p className="hero-copy">돌봄 완료 사진과 추억을 초대된 가족끼리만 나눠요.</p><div className="album-grid"><span>✿</span><span>☀</span><span>♡</span><span>✦</span></div><button className="primary-button wide-button" onClick={() => go('plan')}>Pro 기능 살펴보기</button></>
  if (boot && screen === 'programs') page = <><div className="eyebrow">돌봄 제도 내비게이터 <Pro /></div><h2 className="hero-title">우리 동네<br />돌봄 혜택</h2><p className="hero-copy">가족에게 맞는 돌봄 지원 제도를 찾아드려요.</p><Card className="simple-list-card"><span className="calendar-icon">▦</span><div><strong>늘봄학교</strong><p>방과 후 돌봄 프로그램</p></div></Card><Card className="simple-list-card"><span className="calendar-icon">♡</span><div><strong>조부모 돌봄 지원</strong><p>지역별 지원 기준 확인</p></div></Card><button className="primary-button wide-button" onClick={() => go('plan')}>Pro 기능 살펴보기</button></>

  const isRootScreen = ['home', 'family', 'assignments', 'tasks', 'members'].includes(screen)
  const top = isRootScreen
    ? <header className="top-bar home-bar"><div><h1>가족</h1><p>{today}{screen === 'tasks' ? ' · ' + member(viewer) : ''}</p></div><div className="top-actions"><button className="bell" aria-label="알림함" onClick={() => go('notifications')}>♧{unread > 0 && <span className="bell-count">{unread}</span>}</button><button className="avatar" aria-label="가족 구성원" onClick={() => go('members')}>가</button></div></header>
    : <header className="top-bar detail-bar"><button className="back" aria-label="뒤로 가기" onClick={() => go(screen === 'review' ? 'family' : 'home')}>‹</button><h1>{title}</h1><span className="top-spacer" /></header>

  return <div className="app-shell"><aside className="screen-index"><div className="brand"><span className="brand-mark">LG</span><div><strong>Family Care</strong><small>기능 목업 개발 버전</small></div></div><p className="index-intro">Figma 기능 페이지의 주요 흐름을 화면별로 확인할 수 있어요.</p>{groups.map(g => <div key={g.title} className="index-group"><h2>{g.title}</h2>{g.pages.map(([id, label]) => <button key={id} className={screen === id ? 'active' : ''} onClick={() => go(id)}>{label}</button>)}</div>)}</aside>
    <div className="phone-wrap"><div className="phone"><div className="status-bar"><span>2:18</span><span className="status-icons">▰▰▰ 72%</span></div>{top}<main className="phone-content">{page}</main>{isRootScreen && <button className="floating-capture" aria-label="돌봄 정보 등록" onClick={() => go('capture')}>＋</button>}<nav className="bottom-nav" aria-label="주요 메뉴"><button className={screen === 'home' ? 'active' : ''} onClick={() => go('home')}><span>⌂</span>홈</button><button onClick={() => go('settings')}><span>▣</span>디바이스</button><button className={['assignments', 'tasks', 'handoff', 'exception'].includes(screen) ? 'active' : ''} onClick={() => go('assignments')}><span>♡</span>케어</button><button className={['family', 'capture', 'review', 'members'].includes(screen) ? 'active' : ''} onClick={() => go('family')}><span>♧</span>가족{pending.length > 0 && <i>{pending.length}</i>}</button><button onClick={() => go('members')}><span>☰</span>메뉴</button></nav></div>{error && <div className="error-toast" role="alert"><button aria-label="닫기" onClick={() => setError('')}>×</button>{error}</div>}{toast && <div className="success-toast" role="status">{toast}</div>}</div>
    {showSheet && <div className="sheet-overlay" onClick={() => setShowSheet(false)}><div className="bottom-sheet" onClick={e => e.stopPropagation()}><div className="sheet-handle" /><h2>특이사항이 있었나요?</h2><p>남긴 내용은 다음 담당자에게 필요한 때 전달돼요.</p><textarea className="text-area" rows={4} value={note} onChange={e => setNote(e.target.value)} placeholder="없으면 빈칸으로 완료해도 돼요" /><button className="primary-button wide-button" onClick={complete}>완료하고 가족에게 알리기</button><button className="text-link centered" onClick={() => setShowSheet(false)}>돌아가기</button></div></div>}
  </div>
}

export default App
